name: Flutter Build & Release

on:
  push:
    tags:
      - 'v*'   # Trigger on version tags like v1.0.0+7

permissions:
  contents: write   # Needed for GitHub Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'  # Dart 3.8.1 compatible

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build Android APK
      - name: Build APK
        run: flutter build apk --release

      # Build Android App Bundle (AAB)
      - name: Build AAB
        run: flutter build appbundle --release

      # Create GitHub Release and Upload APK + AAB
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
