name: Flutter Build & Release

on:
  push:
    tags:
      - 'v*'   # Trigger on version tags

permissions:
  contents: write   # Needed for GitHub Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Upload APK & AAB
        uses: actions/upload-artifact@v4
        with:
          name: offlinebingo-builds
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
          if-no-files-found: error
          overwrite: true
          retention-days: 7

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: offlinebingo-builds
          path: artifacts

      - name: Rename artifacts for release
        run: |
          mv artifacts/build/app/outputs/flutter-apk/app-release.apk artifacts/offlinebingo-${{ github.ref_name }}.apk
          mv artifacts/build/app/outputs/bundle/release/app-release.aab artifacts/offlinebingo-${{ github.ref_name }}.aab

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/offlinebingo-${{ github.ref_name }}.apk
            artifacts/offlinebingo-${{ github.ref_name }}.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
