name: Flutter Build & Release

on:
  push:
    tags:
      - 'v*'   # Runs only when you push a tag like v1.0.0, v1.2.3
permissions:
  contents: write   # Needed for GitHub Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'

      - run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk#yeneBingo-${{ github.ref_name }}.apk
            build/app/outputs/bundle/release/app-release.aab#yeneBingo-${{ github.ref_name }}.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
